name: Pull request

on: pull_request

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build VSIX extension file
        uses: HaaLeo/publish-vscode-extension@v1
        id: vsix-build
        with:
          dryRun: true
          pat: stub

      - name: Archive the extension build file
        uses: actions/upload-artifact@v3
        with:
          name: extension
          path: "*.vsix"
          retention-days: 1

  prow:
    name: Prow
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v1.1.3
        with:
          jobs: "lgtm"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
